<?php


namespace ziya\ClockPicker;


use yii\base\Exception;
use yii\base\Widget;
use yii\helpers\Html;
use yii\web\View;

class ClockPicker extends Widget
{
    public $bootstrap = true;
    public $name;
    public $value;
    public $model;
    public $attribute;
    public $options=[];

    public function init()
    {
        parent::init();
        if ($this->bootstrap) {
            $view = $this->getView();
            ClockPickerBootstrapAssets::register($view);
        } else {
            $view = $this->getView();
            ClockPickerJqueryAssets::register($view);
        }
    }

    /**
     * @return bool
     * @throws Exception
     */
    public function beforeRun()
    {
        $this->validate();
        return parent::beforeRun(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws Exception
     */
    public function validate()
    {
        if ($this->model!== null) {
            if ($this->attribute === null) {
                throw new Exception('attribute property must be specified when used with model');
            }
        } else {
            if  ($this->name === null) {
                throw new Exception('name property must be set when used without model');
            }
        }

    }

    public function input()
    {
        if ($this->model !== null) {
            return Html::activeTextInput($this->model,$this->attribute,['class'=>'form-control']);
        }
        return Html::textInput($this->name,$this->value,['class'=>'form-control']);
    }

    /**
     * @return string
     */
    public function run()
    {
        $this->getView()->registerJs("
         $('.clockpicker').clockpicker();
        ",View::POS_END);
        return Html::tag('div',
            $this->input()
            .Html::tag(
                'span',
                Html::tag(
                    'span',
                    '',
                    ['class'=>'glyphicon glyphicon-time']
                ),
                ['class'=>'input-group-addon']
            ),
            ['class'=>'input-group clockpicker']
        );
    }
}